apps/drinks/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from django.views.generic import TemplateView

from apps.drinks import views

urlpatterns = patterns('',
        url(r'^$', views.index, name='index'),
        url(r'^send/$', views.send, name='send'),
)

piraya/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^members/', include('apps.members.urls')),
    url(r'^drinks/', include('apps.drinks.urls')),
    url(r'^os/', include('apps.otympligaspelen.urls')),
    
    # Keep this last
    url(r'^', include('apps.core.urls')),
)

handler404 = 'apps.core.views.not_found'

apps/drinks/models.py
# -*- coding: utf-8 -*-
from django.db import models

class Drink(models.Model):
    name = models.CharField(max_length=64)
    type = models.CharField(max_length=32)
    description = models.TextField()
    sent_by = models.CharField(max_length=64)
    hits = models.IntegerField(default=0)
    votes = models.IntegerField(default=0)
    total_votes = models.IntegerField(default=0)
    approved = models.BooleanField(default=False)

    def __unicode__(self):
        return self.name

class Ingridient(models.Model):
    name = models.CharField(max_length=64)
    quantity = models.CharField(max_length=32)
    drink = models.ForeignKey(Drink)
    
    def __unicode__(self):
        return self.name

apps/drinks/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from django.http import HttpResponseRedirect

def index(request):
    return render(request, 'drinks/index.html')

def send(request):
    if request.method == "GET":
        print 'GET'
        return render(request, 'drinks/send.html', {'error': False})
    elif request.method == "POST":
        pass
        try:
            # Get POST data
            num_ingredients = int(request.POST['num_ing'])
            ingredients = []
            for n in range(num_ingredients):
                ingredients.append({
                    'name': request.POST['ing%d' % n],
                    'quantity': request.POST['qua%d' % n],
                })
            
            drink = {
                'name': request.POST['name'],
                'ingredients': ingredients,
                'description': request.POST['description'],
                'type': request.POST['type'],
                'sent_by': request.POST['sentby'],
            }
        except (KeyError, ValueError):
            # Invalid input
            return render(request, 'drinks/send.html', {'error': True})
        else:
            # Try to add drink
            if not Drink.addNewDrink(drink):
                # Invalid input
                return render(request, 'drinks/send.html', {'error': True})
            
            # This prevents data from being posted twice if a
            # user hits the Back button.
            return HttpResponseRedirect()

apps/drinks/templates/drinks/index.html
{% extends "core/base.html" %}

{% block content %}

<h1>Drinkrecept</h1>
<div class="part">
    Puss
</div>

{% endblock %}

apps/drinks/templates/drinks/send.html
{% extends "core/base.html" %}
{% load staticfiles %}

{% block javascript %}
<script src="{% static 'js/jquery-1.10.2.js' %}"></script>
<script>
$(document).ready(function() {
    var num_ing = 1;
    
    $("#add_ingredient").click(function() {
        num_ing++;
        
        $("#num_ingredients").val(num_ing);
        $("#ingredients").append(
            '<div id="ing' + (num_ing - 1) + '">Ingrediens ' + num_ing + ': <input type="text" name="ing' + (num_ing - 1) + '"> Kvantitet: <input type="text" name="qua' + (num_ing - 1) + '"></div>'
        );
        
        if (num_ing == 8) {
            $("#add_ingredient").attr("disabled", "disabled");
        }
        if (num_ing > 1) {
            $("#rem_ingredient").removeAttr("disabled");
        }
    });
    
    $("#rem_ingredient").click(function() {
        num_ing--;
        $("#ing" + num_ing).remove();        
        $("#num_ingredients").val(num_ing);
        if (num_ing < 8) {
            $("#add_ingredient").removeAttr("disabled");
        }
        if (num_ing == 1) {
            $("#rem_ingredient").attr("disabled", "disabled");
        }
    });
});
</script>
{% endblock %}

{% block content %}
<h1>Drinkrecept</h1>
<div class="part">
    <h2>Skicka in en drink</h2>
    <form action="/drinks/add/" method="post">
        {% csrf_token %}
        <div>
            <label for="id_name">Drinkens namn:</label>
            <input id="id_name" type="text" name="name">
        </div>
        <br>
        <div>
            <label for="id_num_ing">Antal ingredienser:</label>
            <select id="id_num_ing">
                <option value="1">1</option>
                <option value="2">2</option>
            </select>
            <br>
            <input id="num_ingredients" type="hidden" name="num_ingredients" value="1">
            <label for="id_ing_0">Ingrediens:</label>
            <input id="id_ing_0" type="text" name="ing_0">
            <label for="id_qua_0">Kvantitet:</label>
            <input id="id_qua_0" type="text" name="qua0">
        </div>
        <br>
        <div>
            <label for="id_description">Beskrivning, hur den blandas till, med mera:</label>
            <textarea id="id_description" name="description" cols="50" rows="8"></textarea>
            <br>
            <label for="id_type">Typ:</label>
            <select id="id_type" name="type">
                <option value="Drink">Drink</option>
                <option value="Shot">Shot</option>
            </select>
            <br>
            <label for="id_sentby">Inskickad av:</label>
            <input id="id_sentby" type="text" name="sentby">
        </div>
        <br>
        <input type="submit" value="Skicka!">
    </form>
</div>
{% endblock %}